name: Tests CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Build with Gradle
        working-directory: ./ConsoleOrganizer
        run: ./gradlew build

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        working-directory: ./ConsoleOrganizer
        run: docker build . --tag console-organizer:$(date +%s)
